version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: trigon-db
    environment:
      POSTGRES_DB: trigon
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
  
volumes:
  db-data:

networks:
  backend:
    driver: bridge